Minor adjustments

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -20,7 +20,7 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Set fap path
+    - name: Set fap source path
       shell: bash
       run: >
         if [ -z ${{ inputs.path }} ]; then
@@ -45,8 +45,7 @@ runs:
         elif [ ${{ inputs.channel }} = 'release' ]; then
           echo "CHANNEL=2" >> $GITHUB_ENV
         else
-          echo "::error::channel: Bad input!"
-          exit 1
+          echo "::error::channel: Bad input!"; exit 1
         fi
 
     - name: Get commit id
@@ -67,7 +66,7 @@ runs:
           ${{ runner.os }}-${{ env.cache-name }}-${{ inputs.channel }}-${{ env.COMMIT_ID }}
 
     - if: ${{ steps.cache-fbt.outputs.cache-hit != 'true' }}
-      name: Update fbt if cache not found
+      name: Update ufbt if cache not found
       shell: bash
       run: ufbt update --channel=${{ inputs.channel }}
 
@@ -76,16 +75,13 @@ runs:
       run: >
         if [ -z ${{ inputs.lint_only }} ]; then
           echo "::add-matcher::$GITHUB_WORKSPACE/problem_matcher.json";
-          cd ${{ env.FAP_PATH }};
-          ufbt;
+          cd ${{ env.FAP_PATH }}; ufbt;
           echo "ARTIFACT=$(basename ${{ env.FAP_PATH }}/dist/*.fap)" >> $GITHUB_ENV;
         elif [ ${{ inputs.lint_only }} = 'true' ]; then
           echo "::add-matcher::$GITHUB_WORKSPACE/problem_matcher.json";
-          cd ${{ env.FAP_PATH }};
-          ufbt lint
+          cd ${{ env.FAP_PATH }}; ufbt lint
         else
-          echo "::error::lint_only: Bad input!"
-          exit 1
+          echo "::error::lint_only: Bad input!"; exit 1
         fi
 
     - if: ${{ inputs.lint_only == 'false' }}
